name       : memcached
version    : 1.6.9
release    : 10
source     :
    - https://github.com/memcached/memcached/archive/refs/tags/1.6.9.tar.gz : be36d7104ef9460c1d563b6aaf840733beeb61b75ae672dfb79d3b486a653fdc
license    : BSD-3-Clause
component  : network.web
summary    : Free & open source, high-performance, distributed memory object caching system
description: |
    Free & open source, high-performance, distributed memory object caching system
builddeps  :
    - pkgconfig(libevent)
setup      : |
    sed -i "s|/etc/sysconfig/memcached|/etc/memcached.conf|" scripts/memcached.service
    %autogen --enable-64bit
build      : |
    %make
install    : |
    %make_install
    install -D -m 00644 doc/memcached.1 $installdir/usr/share/man/man1/memcached.1
    install -D -m 00644 scripts/memcached-tool.1 $installdir/usr/share/man/man1/memcached-tool.1
    install -D -m 00644 scripts/memcached.service $installdir/usr/lib/systemd/system/memcached.service
    install -D -m 00755 scripts/memcached-tool $installdir/usr/bin/memcached-tool
check      : |
    %make test
