name       : memcached
version    : 1.5.4
release    : 3
source     :
    - http://www.memcached.org/files/memcached-1.5.4.tar.gz : e0c3cfa89fa4c2ffd8aa45df7825c6d1a2423ac89ab1a7c4f42bb9803f7403d4
license    : BSD-3-Clause
component  : network.web
summary    : Free & open source, high-performance, distributed memory object caching system
description: |
    Free & open source, high-performance, distributed memory object caching system
builddeps  :
    - pkgconfig(libevent)
setup      : |
    sed -i "s|/etc/sysconfig/memcached|/etc/memcached.conf|" scripts/memcached.service
    %configure --enable-64bit
build      : |
    %make
install    : |
    %make_install
    install -D -m 00644 doc/memcached.1 $installdir/usr/share/man/man1/memcached.1
    install -D -m 00644 scripts/memcached-tool.1 $installdir/usr/share/man/man1/memcached-tool.1
    install -D -m 00644 scripts/memcached.service $installdir/usr/lib/systemd/system/memcached.service
    install -D -m 00755 scripts/memcached-tool $installdir/usr/bin/memcached-tool
