name       : memcached
version    : 1.6.19
release    : 11
source     :
    - https://github.com/memcached/memcached/archive/refs/tags/1.6.19.tar.gz : 08916af20e31b4ef83925c740d6396c4cea9344cfa298f9653be408ec470d0ff
homepage   : https://memcached.org/
license    : BSD-3-Clause
component  : network.web
summary    : Free & open source, high-performance, distributed memory object caching system
description: |
    Free & open source, high-performance, distributed memory object caching system, generic in nature, but intended for use in speeding up dynamic web applications by alleviating database load.
builddeps  :
    - pkgconfig(libevent)
setup      : |
    sed -i "s|/etc/sysconfig/memcached|/etc/memcached.conf|" scripts/memcached.service
    %autogen --enable-64bit
build      : |
    %make
install    : |
    %make_install
    install -Dm00644 doc/memcached.1 $installdir/usr/share/man/man1/memcached.1
    install -Dm00644 scripts/memcached-tool.1 $installdir/usr/share/man/man1/memcached-tool.1
    install -Dm00644 scripts/memcached.service $installdir/usr/lib/systemd/system/memcached.service
    install -Dm00755 scripts/memcached-tool $installdir/usr/bin/memcached-tool
check      : |
    %make test
