name       : memcached
version    : 1.5.16
release    : 6
source     :
    - https://github.com/memcached/memcached/archive/1.5.16.tar.gz : a0c1a7e72186722d7c0e9d5527a63beb339b933d768687f183e163adf935c662
license    : BSD-3-Clause
component  : network.web
summary    : Free & open source, high-performance, distributed memory object caching system
description: |
    Free & open source, high-performance, distributed memory object caching system
builddeps  :
    - pkgconfig(libevent)
setup      : |
    sed -i "s|/etc/sysconfig/memcached|/etc/memcached.conf|" scripts/memcached.service
    %autogen --enable-64bit
build      : |
    %make
install    : |
    %make_install
    install -D -m 00644 doc/memcached.1 $installdir/usr/share/man/man1/memcached.1
    install -D -m 00644 scripts/memcached-tool.1 $installdir/usr/share/man/man1/memcached-tool.1
    install -D -m 00644 scripts/memcached.service $installdir/usr/lib/systemd/system/memcached.service
    install -D -m 00755 scripts/memcached-tool $installdir/usr/bin/memcached-tool
check      : |
    %make test
